apiVersion: apps/v1

kind: Deployment

metadata:
  name: result

spec:
  selector:
    matchLabels:
      app: result
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 0
           maxUnavailable: 100%    
  replicas: 2
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
      containers:
      - image: samarthr8/webclues-assignment:latest
        name: result
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "500Mi"
              cpu: .5
            limits:
              memory: "1000Mi"
              cpu: 1

---

apiVersion: v1

kind: Service

metadata:
  name: result
  labels:
    app: result

spec:
  selector:
    app: result
  type: LoadBalancer
  ports:
  - name: "result-service"
    protocol: TCP
    port: 3000
    targetPort: 80
